import type { PoolClient } from 'pg';
import { transaction } from '../config/db';

const PLATINUM_ONE_TIER = 20;

type Queryable = Pick<PoolClient, 'query'>;

export interface PartyTrackingResult {
  groupsInserted: number;
  pairsInserted: number;
}

/**
 * Persist one match's ranked party facts and update exact-stack/pair projections.
 *
 * The match fact tables are the idempotency boundary. A retry inserts zero
 * facts, so it also adds zero to either aggregate. player_ids are sorted by SQL
 * and every pair is generated by ordinal low<high, making A+B identical to B+A.
 */
export async function recordRankedPartyGroups(
  matchId: number,
  entryDatetime: string | Date,
): Promise<PartyTrackingResult> {
  if (!Number.isInteger(matchId) || matchId <= 0) throw new Error(`Invalid match id ${matchId}`);
  if (Number.isNaN(new Date(entryDatetime).getTime())) {
    throw new Error(`Invalid entry datetime for match ${matchId}`);
  }

  return transaction(async client => {
    await client.query('SELECT pg_advisory_xact_lock($1)', [matchId]);

    const groups = await client.query<{ inserted_count: number }>(`
      WITH grouped AS (
        SELECT
          mp.match_id,
          mp.task_force,
          mp.party_id AS observed_party_id,
          array_agg(DISTINCT mp.player_id ORDER BY mp.player_id) AS player_ids,
          count(DISTINCT mp.player_id)::SMALLINT AS stack_size,
          COALESCE(max(mp.league_tier) FILTER (WHERE mp.league_tier > 0), 0)::SMALLINT AS max_known_tier,
          min(mp.entry_datetime) AS entry_datetime
        FROM match_players mp
        JOIN matches m
          ON m.match_id = mp.match_id
         AND m.entry_datetime = mp.entry_datetime
        WHERE mp.match_id = $1
          AND mp.entry_datetime = $3::timestamptz
          AND m.queue_id = 486
          AND COALESCE(m.is_ranked, TRUE)
          AND mp.player_id > 0
          AND mp.party_id IS NOT NULL
          AND mp.party_id <> 0
          AND mp.task_force IN (1, 2)
          AND mp.champion_id > 0
          AND COALESCE(mp.source, 'direct') IN ('direct', 'recovered')
        GROUP BY mp.match_id, mp.task_force, mp.party_id
      ), eligible AS (
        SELECT
          match_id,
          array_to_string(player_ids, ':') AS group_key,
          player_ids,
          stack_size,
          task_force,
          observed_party_id,
          max_known_tier,
          entry_datetime
        FROM grouped
        WHERE stack_size BETWEEN 2 AND 5
          AND (stack_size = 2 OR max_known_tier <= $2)
      ), inserted AS (
        INSERT INTO match_party_groups (
          match_id, group_key, player_ids, stack_size, task_force,
          observed_party_id, max_known_tier, entry_datetime
        )
        SELECT
          match_id, group_key, player_ids, stack_size, task_force,
          observed_party_id, max_known_tier, entry_datetime
        FROM eligible
        ON CONFLICT (match_id, group_key) DO NOTHING
        RETURNING *
      ), projected AS (
        INSERT INTO party_stack_stats (
          group_key, player_ids, stack_size, match_count, first_seen, last_seen, updated_at
        )
        SELECT group_key, player_ids, stack_size, 1, entry_datetime, entry_datetime, now()
        FROM inserted
        ON CONFLICT (group_key) DO UPDATE SET
          match_count = party_stack_stats.match_count + EXCLUDED.match_count,
          first_seen = LEAST(party_stack_stats.first_seen, EXCLUDED.first_seen),
          last_seen = GREATEST(party_stack_stats.last_seen, EXCLUDED.last_seen),
          updated_at = now()
        RETURNING 1
      )
      SELECT count(*)::INT AS inserted_count FROM inserted
    `, [matchId, PLATINUM_ONE_TIER, entryDatetime]);

    const pairs = await client.query<{ inserted_count: number }>(`
      WITH candidates AS (
        SELECT
          mpg.match_id,
          low.player_id AS player_low_id,
          high.player_id AS player_high_id,
          mpg.group_key AS source_group_key,
          mpg.entry_datetime
        FROM match_party_groups mpg
        CROSS JOIN LATERAL unnest(mpg.player_ids) WITH ORDINALITY AS low(player_id, ordinal)
        CROSS JOIN LATERAL unnest(mpg.player_ids) WITH ORDINALITY AS high(player_id, ordinal)
        WHERE mpg.match_id = $1
          AND low.ordinal < high.ordinal
      ), inserted AS (
        INSERT INTO match_party_pairs (
          match_id, player_low_id, player_high_id, source_group_key, entry_datetime
        )
        SELECT match_id, player_low_id, player_high_id, source_group_key, entry_datetime
        FROM candidates
        ON CONFLICT (match_id, player_low_id, player_high_id) DO NOTHING
        RETURNING *
      ), grouped AS (
        SELECT
          player_low_id,
          player_high_id,
          count(*)::INT AS match_count,
          min(entry_datetime) AS first_seen,
          max(entry_datetime) AS last_seen
        FROM inserted
        GROUP BY player_low_id, player_high_id
      ), projected AS (
        INSERT INTO party_pair_stats (
          player_low_id, player_high_id, match_count, first_seen, last_seen, updated_at
        )
        SELECT player_low_id, player_high_id, match_count, first_seen, last_seen, now()
        FROM grouped
        ON CONFLICT (player_low_id, player_high_id) DO UPDATE SET
          match_count = party_pair_stats.match_count + EXCLUDED.match_count,
          first_seen = LEAST(party_pair_stats.first_seen, EXCLUDED.first_seen),
          last_seen = GREATEST(party_pair_stats.last_seen, EXCLUDED.last_seen),
          updated_at = now()
        RETURNING 1
      )
      SELECT count(*)::INT AS inserted_count FROM inserted
    `, [matchId]);

    return {
      groupsInserted: Number(groups.rows[0]?.inserted_count || 0),
      pairsInserted: Number(pairs.rows[0]?.inserted_count || 0),
    };
  });
}

/** Rebuild both aggregate projections from immutable match facts. */
export async function rebuildPartyTrackingProjections(client: Queryable): Promise<void> {
  await client.query('DELETE FROM party_stack_stats');
  await client.query(`
    INSERT INTO party_stack_stats (
      group_key, player_ids, stack_size, match_count, first_seen, last_seen, updated_at
    )
    SELECT
      group_key, player_ids, stack_size, count(DISTINCT match_id)::INT,
      min(entry_datetime), max(entry_datetime), now()
    FROM match_party_groups
    GROUP BY group_key, player_ids, stack_size
  `);

  await client.query('DELETE FROM party_pair_stats');
  await client.query(`
    INSERT INTO party_pair_stats (
      player_low_id, player_high_id, match_count, first_seen, last_seen, updated_at
    )
    SELECT
      player_low_id, player_high_id, count(DISTINCT match_id)::INT,
      min(entry_datetime), max(entry_datetime), now()
    FROM match_party_pairs
    GROUP BY player_low_id, player_high_id
  `);
}
