use std::collections::HashMap;
use axum::{Json, Router, extract::{Extension, Path, Query, State}, http::{HeaderMap, HeaderValue, StatusCode, header::CACHE_CONTROL}, response::{IntoResponse, Response}, routing::{get, post, put}};
use paladinscat_core::database::Database;
use serde_json::{Value, json};
use crate::{error::ApiError, request::RequestId, routes::{admin::is_project_staff_session, identity::{as_i64, parse_id, require_session, session, simple_error}}};

pub const ROUTE_COUNT: usize = 8;
#[derive(Clone)] struct OperationsState { database: Database }
pub fn router(database: Database) -> Router { Router::new()
    .route("/tickets", get(list_tickets).post(create_ticket))
    .route("/tickets/{id}", get(ticket_detail).put(update_ticket))
    .route("/tickets/{id}/comments", post(add_comment))
    .route("/projects", get(list_projects).post(create_project))
    .route("/projects/{id}", put(update_project))
    .with_state(OperationsState { database }) }

fn text(body:&Value,key:&str,max:usize)->String { body.get(key).and_then(Value::as_str).unwrap_or_default().trim().chars().take(max).collect() }
fn page(query:&HashMap<String,String>)->(i64,i64) { let p=query.get("page").and_then(|v|parse_id(v)).unwrap_or(1); let s=query.get("per_page").and_then(|v|parse_id(v)).unwrap_or(20).clamp(1,50); (p,s) }
fn ticket_row_sql() -> &'static str { "SELECT t.id,('PC-'||t.id)::TEXT AS code,t.kind,t.status,t.title,t.details,t.created_at,t.updated_at,u.username AS requester FROM tickets t JOIN users u ON u.id=t.requester_user_id" }
fn private_response(value:Value)->Response { let mut r=(StatusCode::OK,Json(value)).into_response(); r.headers_mut().insert(CACHE_CONTROL,HeaderValue::from_static("private, no-store")); r }
async fn list_tickets(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,Query(query):Query<HashMap<String,String>>) -> Result<Response,ApiError> { let (p,s)=page(&query); let offset=(p-1)*s; let rows=state.database.query_json(&format!("{} ORDER BY t.created_at DESC,t.id DESC LIMIT $1 OFFSET $2",ticket_row_sql()), &[&s,&offset]).await.map_err(|e|ApiError::database(e,&request_id))?; let total=state.database.one_json("SELECT count(*)::INT AS total FROM tickets",&[]).await.map_err(|e|ApiError::database(e,&request_id))?.and_then(|r|as_i64(r.get("total"))).unwrap_or(0); Ok(private_response(json!({"data":rows,"page":{"current":p,"size":s,"total":total,"total_pages":(total+s-1)/s}}))) }
async fn create_ticket(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,headers:HeaderMap,Json(body):Json<Value>) -> Result<Response,ApiError> { let user=match require_session(&state.database,&headers,&request_id).await {Ok(v)=>v,Err(r)=>return Ok(r)}; let kind=text(&body,"kind",16); let title=text(&body,"title",180); let details=text(&body,"details",10_000); if !matches!(kind.as_str(),"bug"|"feature")||title.is_empty()||details.is_empty(){return Ok(simple_error(StatusCode::BAD_REQUEST,"A type, title, and details are required"));} let ticket=state.database.one_json("INSERT INTO tickets(requester_user_id,kind,title,details) VALUES($1,$2,$3,$4) RETURNING id",&[&user.user_id,&kind,&title,&details]).await.map_err(|e|ApiError::database(e,&request_id))?.ok_or_else(||ApiError::internal(&request_id))?; let id=as_i64(ticket.get("id")).unwrap_or_default(); state.database.query_json("INSERT INTO user_notifications(user_id,actor_user_id,type,ticket_id) SELECT id,$1,'ticket_created',$2 FROM users WHERE (role IN ('developer','admin') OR is_admin) AND id<>$1",&[&user.user_id,&id]).await.map_err(|e|ApiError::database(e,&request_id))?; let row=state.database.one_json(&format!("{} WHERE t.id=$1",ticket_row_sql()),&[&id]).await.map_err(|e|ApiError::database(e,&request_id))?.unwrap_or(Value::Null); Ok((StatusCode::CREATED,Json(row)).into_response()) }
async fn ticket_detail(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,Path(id):Path<String>) -> Result<Response,ApiError> { let Some(id)=parse_ticket(&id) else{return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid ticket"))}; let ticket=state.database.one_json(&format!("{} WHERE t.id=$1",ticket_row_sql()),&[&id]).await.map_err(|e|ApiError::database(e,&request_id))?; let Some(ticket)=ticket else{return Ok(simple_error(StatusCode::NOT_FOUND,"Ticket not found"))}; let comments=state.database.query_json("SELECT c.id,c.body,c.created_at,u.username AS author FROM ticket_comments c JOIN users u ON u.id=c.author_user_id WHERE c.ticket_id=$1 ORDER BY c.created_at,c.id",&[&id]).await.map_err(|e|ApiError::database(e,&request_id))?; Ok(private_response(json!({"ticket":ticket,"comments":comments}))) }
fn parse_ticket(id:&str)->Option<i64>{ parse_id(id.strip_prefix("PC-").unwrap_or(id)) }
async fn ticket_access(state:&OperationsState,headers:&HeaderMap,request_id:&RequestId,id:i64)->Result<Result<(crate::routes::identity::Session,bool),Response>,ApiError>{ let user=match require_session(&state.database,headers,request_id).await{Ok(v)=>v,Err(r)=>return Ok(Err(r))};let row=state.database.one_json("SELECT requester_user_id FROM tickets WHERE id=$1",&[&id]).await.map_err(|e|ApiError::database(e,request_id))?;let Some(row)=row else{return Ok(Err(simple_error(StatusCode::NOT_FOUND,"Ticket not found")))};let staff=is_project_staff_session(Some(&user));if !staff&&as_i64(row.get("requester_user_id"))!=Some(i64::from(user.user_id)){return Ok(Err(simple_error(StatusCode::FORBIDDEN,"Not allowed to update this ticket")))} Ok(Ok((user,staff)))}
async fn add_comment(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,Path(id):Path<String>,headers:HeaderMap,Json(body):Json<Value>)->Result<Response,ApiError>{let Some(id)=parse_ticket(&id)else{return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid ticket"))};let (user,staff)=match ticket_access(&state,&headers,&request_id,id).await?{Ok(v)=>v,Err(r)=>return Ok(r)};let body=text(&body,"body",2_000);if body.is_empty(){return Ok(simple_error(StatusCode::BAD_REQUEST,"Comment is required"))};let row=state.database.one_json("INSERT INTO ticket_comments(ticket_id,author_user_id,body) VALUES($1,$2,$3) RETURNING id",&[&id,&user.user_id,&body]).await.map_err(|e|ApiError::database(e,&request_id))?.unwrap_or(Value::Null);let cid=as_i64(row.get("id")).unwrap_or_default();if staff {state.database.query_json("INSERT INTO user_notifications(user_id,actor_user_id,type,ticket_id,ticket_comment_id) SELECT requester_user_id,$1,'ticket_comment',$2,$3 FROM tickets WHERE id=$2 AND requester_user_id<>$1 ON CONFLICT DO NOTHING",&[&user.user_id,&id,&cid]).await.map_err(|e|ApiError::database(e,&request_id))?;}else{state.database.query_json("INSERT INTO user_notifications(user_id,actor_user_id,type,ticket_id,ticket_comment_id) SELECT id,$1,'ticket_comment',$2,$3 FROM users WHERE (role IN ('developer','admin') OR is_admin) AND id<>$1 ON CONFLICT DO NOTHING",&[&user.user_id,&id,&cid]).await.map_err(|e|ApiError::database(e,&request_id))?;} Ok(ticket_detail(State(state),Extension(request_id),Path(id.to_string())).await?)}
async fn update_ticket(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,Path(id):Path<String>,headers:HeaderMap,Json(body):Json<Value>)->Result<Response,ApiError>{let Some(id)=parse_ticket(&id)else{return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid ticket"))};let(user,staff)=match ticket_access(&state,&headers,&request_id,id).await?{Ok(v)=>v,Err(r)=>return Ok(r)};if !staff{return Ok(simple_error(StatusCode::FORBIDDEN,"Not allowed to change ticket status"))};let status=text(&body,"status",32);if !matches!(status.as_str(),"received"|"under_review"|"planned"|"closed"){return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid status"))};let changed=state.database.one_json("UPDATE tickets SET status=$1,updated_at=now() WHERE id=$2 AND status<>$1 RETURNING id",&[&status,&id]).await.map_err(|e|ApiError::database(e,&request_id))?;if changed.is_some(){state.database.query_json("INSERT INTO user_notifications(user_id,actor_user_id,type,ticket_id) SELECT requester_user_id,$1,'ticket_status',$2 FROM tickets WHERE id=$2 AND requester_user_id<>$1",&[&user.user_id,&id]).await.map_err(|e|ApiError::database(e,&request_id))?;} Ok(ticket_detail(State(state),Extension(request_id),Path(id.to_string())).await?)}
async fn staff(state:&OperationsState,headers:&HeaderMap,request_id:&RequestId)->Result<Result<crate::routes::identity::Session,Response>,ApiError>{match session(&state.database,headers,request_id).await?{Some(s) if is_project_staff_session(Some(&s))=>Ok(Ok(s)),_=>Ok(Err(simple_error(StatusCode::UNAUTHORIZED,"Operations access required")))}}
async fn list_projects(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,headers:HeaderMap)->Result<Response,ApiError>{if let Err(r)=staff(&state,&headers,&request_id).await?{return Ok(r)};let rows=state.database.query_json("SELECT id,('WORK-'||id)::TEXT AS code,title,component,column_name,priority,assignee,details,created_at,updated_at FROM project_work_items ORDER BY updated_at DESC,id DESC",&[]).await.map_err(|e|ApiError::database(e,&request_id))?;Ok(private_response(json!({"data":rows})))}
async fn create_project(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,headers:HeaderMap,Json(body):Json<Value>)->Result<Response,ApiError>{let user=match staff(&state,&headers,&request_id).await?{Ok(v)=>v,Err(r)=>return Ok(r)};let title=text(&body,"title",180);let component=text(&body,"component",120);if title.is_empty()||component.is_empty(){return Ok(simple_error(StatusCode::BAD_REQUEST,"Title and project are required"))};let row=state.database.one_json("INSERT INTO project_work_items(title,component,created_by_user_id,updated_by_user_id) VALUES($1,$2,$3,$3) RETURNING id",&[&title,&component,&user.user_id]).await.map_err(|e|ApiError::database(e,&request_id))?.unwrap_or(Value::Null);Ok((StatusCode::CREATED,Json(row)).into_response())}
async fn update_project(State(state):State<OperationsState>,Extension(request_id):Extension<RequestId>,Path(id):Path<String>,headers:HeaderMap,Json(body):Json<Value>)->Result<Response,ApiError>{let user=match staff(&state,&headers,&request_id).await?{Ok(v)=>v,Err(r)=>return Ok(r)};let Some(id)=parse_id(&id)else{return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid task"))};let title=text(&body,"title",180);let component=text(&body,"component",120);let column=text(&body,"column",16);let priority=text(&body,"priority",16);let assignee=text(&body,"assignee",120);let details=text(&body,"details",10_000);if title.is_empty()||component.is_empty()||!matches!(column.as_str(),"backlog"|"building"|"review"|"done")||!matches!(priority.as_str(),"low"|"normal"|"high"){return Ok(simple_error(StatusCode::BAD_REQUEST,"Invalid task"))};let row=state.database.one_json("UPDATE project_work_items SET title=$1,component=$2,column_name=$3,priority=$4,assignee=NULLIF($5,''),details=$6,updated_by_user_id=$7,updated_at=now() WHERE id=$8 RETURNING id",&[&title,&component,&column,&priority,&assignee,&details,&user.user_id,&id]).await.map_err(|e|ApiError::database(e,&request_id))?;Ok(match row{Some(r)=>(StatusCode::OK,Json(r)).into_response(),None=>simple_error(StatusCode::NOT_FOUND,"Task not found")})}
